### ISSUE TITLE
Minor version update

### ISSUE THREAD

**Issue by picobulgarelli** [p32929/AndroidAppUpdater#2]
Hi, I've noticed it's not possible to use minor version update like 1.1 or 1.2 etc because the versionCode var is an Int. Do you think it's possible and it makes sense to change the code and to use a Double instead?

Here my json example:

`{
	"versionCode": 1.1,
	"cancellable": true,
	"url": "http://192.168.1.2/app-release.apk"
}`

in this case the 
`if (AppUpdater.getCurrentVersionCode(this@MainActivity) < updateModel.versionCode)` 
return false when the version of the app is 1.0

**Comment by p32929** [comment]
Actually, the version code is not really supposed to be a `double` or `float` as per Android documentations. It is supposed to be an `int`. You should use `1` or `2` instead of floating points like `1.0` or `2.0`.
